# coding=utf-8
"""Neutral integration contract for external receiver pipelines."""

from pilot_proxy.detector_geometry import DetectorFrameLayout

from .defaults import (
    DEFAULT_CHIME_DTV_RECEIVER_PROFILE,
    DEFAULT_CHIME_STREAM_MAP,
    DEFAULT_DETECTOR_CORE_PROFILE,
    DEFAULT_REFERENCE_RECEIVER_PROFILE,
)
from .detector_core import DetectorCoreProfile, load_detector_core_profile
from .packing import PackedDetectorInput, pack_channelized_streams_for_detector
from .receiver_profile import (
    FREQUENCY_ORDER_ASCENDING_RF,
    FREQUENCY_ORDER_DESCENDING_RF,
    ChannelizerProfile,
    ChannelSelection,
    ReceiverProfile,
    default_reference_receiver_profile,
    load_receiver_profile,
    receiver_frequency_to_channel,
    receiver_profile_hash,
    validate_weight_manifest_profile_hash,
)
from .schemas import (
    COMBINE_MODE_COMBINED_STREAMS,
    COMBINE_MODE_PER_STREAM_DIAGNOSTIC,
    DETECTOR_CORE_ID_PILOT_PROXY_CUDA_LOCAL_REFERENCE_POWER_RATIO,
    DETECTOR_CORE_PROFILE_SCHEMA_NAME,
    DETECTOR_CORE_PROFILE_SCHEMA_REVISION,
    DETECTOR_CORE_PROFILE_SCHEMA_TOKEN,
    QUANTIZATION_SCALE_MODE_GLOBAL,
    QUANTIZATION_SCALE_MODE_PER_STREAM,
    QUANTIZATION_SCALE_MODE_PROVIDED,
    RECEIVER_PROFILE_SCHEMA_NAME,
    RECEIVER_PROFILE_SCHEMA_REVISION,
    RECEIVER_PROFILE_SCHEMA_TOKEN,
    STREAM_LAYOUT_SCHEMA_NAME,
    STREAM_LAYOUT_SCHEMA_REVISION,
    STREAM_LAYOUT_SCHEMA_TOKEN,
    STREAM_MAP_SCHEMA_NAME,
    STREAM_MAP_SCHEMA_REVISION,
    STREAM_MAP_SCHEMA_TOKEN,
)
from .stream_layout import (
    InputStreamMap,
    StreamDescriptor,
    build_stream_map_for_channel,
    detector_shape_for_combined_streams,
    detector_shape_for_per_stream_diagnostics,
    layout_uint64_bound_check,
    load_stream_map,
    quantization_metadata,
)
from .weight_generation import (
    generate_weight_table_from_receiver_profile,
    parse_physical_channel_selection,
    write_weight_bank_from_receiver_profile,
)

__all__ = [
    "COMBINE_MODE_COMBINED_STREAMS",
    "COMBINE_MODE_PER_STREAM_DIAGNOSTIC",
    "ChannelSelection",
    "ChannelizerProfile",
    "DETECTOR_CORE_ID_PILOT_PROXY_CUDA_LOCAL_REFERENCE_POWER_RATIO",
    "DETECTOR_CORE_PROFILE_SCHEMA_NAME",
    "DETECTOR_CORE_PROFILE_SCHEMA_REVISION",
    "DETECTOR_CORE_PROFILE_SCHEMA_TOKEN",
    "DEFAULT_CHIME_DTV_RECEIVER_PROFILE",
    "DEFAULT_CHIME_STREAM_MAP",
    "DEFAULT_DETECTOR_CORE_PROFILE",
    "DEFAULT_REFERENCE_RECEIVER_PROFILE",
    "DetectorCoreProfile",
    "DetectorFrameLayout",
    "FREQUENCY_ORDER_ASCENDING_RF",
    "FREQUENCY_ORDER_DESCENDING_RF",
    "InputStreamMap",
    "PackedDetectorInput",
    "QUANTIZATION_SCALE_MODE_GLOBAL",
    "QUANTIZATION_SCALE_MODE_PER_STREAM",
    "QUANTIZATION_SCALE_MODE_PROVIDED",
    "RECEIVER_PROFILE_SCHEMA_NAME",
    "RECEIVER_PROFILE_SCHEMA_REVISION",
    "RECEIVER_PROFILE_SCHEMA_TOKEN",
    "ReceiverProfile",
    "STREAM_LAYOUT_SCHEMA_NAME",
    "STREAM_LAYOUT_SCHEMA_REVISION",
    "STREAM_LAYOUT_SCHEMA_TOKEN",
    "STREAM_MAP_SCHEMA_NAME",
    "STREAM_MAP_SCHEMA_REVISION",
    "STREAM_MAP_SCHEMA_TOKEN",
    "StreamDescriptor",
    "build_stream_map_for_channel",
    "default_reference_receiver_profile",
    "detector_shape_for_combined_streams",
    "detector_shape_for_per_stream_diagnostics",
    "layout_uint64_bound_check",
    "load_detector_core_profile",
    "load_receiver_profile",
    "load_stream_map",
    "pack_channelized_streams_for_detector",
    "generate_weight_table_from_receiver_profile",
    "parse_physical_channel_selection",
    "quantization_metadata",
    "receiver_frequency_to_channel",
    "receiver_profile_hash",
    "validate_weight_manifest_profile_hash",
    "write_weight_bank_from_receiver_profile",
]
